application.env="{{ .Values.global.env }}"
telemetry.version="2.1"
default.parallelization="10"
spark_output_temp_dir="/data/analytics/tmp/"
storage.key.config="{{ .Values.global.sunbird_cloud_storage_provider | default "" }}_storage_key" 
storage.secret.config="{{ .Values.global.sunbird_cloud_storage_provider | default "" }}_storage_secret" 
cloud_storage_type="{{ .Values.global.sunbird_cloud_storage_provider | default "" }}" 
cloud_storage_region="{{ .Values.global.cloud_storage_region }}"

# Joblog Kafka appender config for cluster execution
log.appender.kafka.enable="false"
log.appender.kafka.broker_host="{{ .Values.global.kafka.host }}:{{ .Values.global.kafka.port }}"
log.appender.kafka.topic="{{ .Values.global.env }}.druid.events.log"

# Spark Driver
spark.memory_fraction={{ .Values.spark.memory_fraction }}
spark.storage_fraction={{ .Values.spark.storage_fraction }}
spark.driver_memory={{ .Values.spark.driver_memory }}

#App ID & Channel ID
default.consumption.app.id="no_value"
default.channel.id="in.ekstep"
default.creation.app.id="no_value"

// Metric event config
metric.producer.id="pipeline.monitoring"
metric.producer.pid="dataproduct.metrics"
push.metrics.kafka=true
metric.kafka.broker="{{ .Values.global.kafka.host }}:{{ .Values.global.kafka.port }}"
metric.kafka.topic="{{ .Values.global.env }}.prom.monitoring.metrics"
