name: aws-infra-opentofu

on:
  workflow_dispatch:
    inputs:
      environment_dir:
        description: "Path to OpenTofu environment directory (e.g. opentofu/aws/template)"
        required: true
        type: string
      action:
        description: "Action to perform"
        required: true
        type: choice
        options:
          - init
          - plan
          - apply
          - destroy

permissions:
  contents: read

jobs:
  terragrunt:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      TG_TF_PATH: tofu
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: "1.11.1"

      - name: Setup Terragrunt
        run: |
          wget -O terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v0.96.0/terragrunt_linux_amd64
          chmod +x terragrunt
          sudo mv terragrunt /usr/local/bin/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Create Backend S3 Bucket
        working-directory: ${{ inputs.environment_dir }}
        run: |
          chmod +x create_tf_backend.sh
          ./create_tf_backend.sh
          ls -la
          source tf.sh

      - name: Terragrunt Init
        if: inputs.action == 'init'
        working-directory: ${{ inputs.environment_dir }}
        run: |
          source tf.sh
          terragrunt run --all init

      - name: Terragrunt Plan
        if: inputs.action == 'plan'
        working-directory: ${{ inputs.environment_dir }}
        run: |
          source tf.sh
          terragrunt run --all plan

      - name: Terragrunt Apply
        if: inputs.action == 'apply'
        working-directory: ${{ inputs.environment_dir }}
        run: |
          source tf.sh
          terragrunt run --all apply --auto-approve

  # Please be cautious while running the destroy command as it will delete all the resources created by the apply command
      - name: Terragrunt Destroy
        if: inputs.action == 'destroy'
        working-directory: ${{ inputs.environment_dir }}
        run: |
          source tf.sh
          terragrunt run --all destroy --auto-approve